# Generated by Django 3.2.16 on 2023-01-23 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Digital_Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_image', models.ImageField(blank=True, upload_to='initial_img')),
                ('gen_image', models.ImageField(upload_to='generated_img')),
                ('iterations', models.IntegerField()),
                ('image_strength', models.DecimalField(decimal_places=1, max_digits=2)),
                ('run_time', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_art', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
