# Generated by Django 3.2.16 on 2023-01-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0002_auto_20230124_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digital_art',
            options={'verbose_name': 'Digital_Art'},
        ),
    ]
