# Generated by Django 3.2.16 on 2023-01-23 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0003_alter_digital_art_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digital_art',
            options={'verbose_name': 'Digital_Art', 'verbose_name_plural': 'Digital_Art'},
        ),
    ]
