# Generated by Django 3.2.16 on 2023-01-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0004_alter_digital_art_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='digital_art',
            name='prompt',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
