# Generated by Django 3.2.16 on 2023-01-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0008_alter_digital_art_run_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digital_art',
            name='run_time',
            field=models.IntegerField(),
        ),
    ]
