# Generated by Django 3.2.16 on 2023-01-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0010_digital_arts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Digital_Arts',
        ),
    ]
