# Generated by Django 3.2.16 on 2023-01-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0012_digital_arts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Digital_Art',
        ),
    ]
