# Generated by Django 3.2.16 on 2023-01-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0015_digital_arts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Digital_Art',
        ),
    ]
