# Generated by Django 3.2.16 on 2023-03-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0021_nft_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nft_collection',
            options={'verbose_name': 'NFT_Collection', 'verbose_name_plural': 'NFT_Collection'},
        ),
    ]
