# Generated by Django 3.2.16 on 2023-03-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0022_alter_nft_collection_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NFT_Collection',
        ),
    ]
