# Generated by Django 3.2.16 on 2023-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0024_nft_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft_collection',
            name='logo',
            field=models.ImageField(blank=True, default='upload_img.jpg', upload_to='collection_logos/'),
        ),
    ]
