# Generated by Django 3.2.16 on 2023-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0026_alter_nft_collection_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft_collection',
            name='logo',
            field=models.ImageField(default='default-collection.avif', upload_to='collection_logos/'),
        ),
    ]
