# Generated by Django 3.2.16 on 2023-03-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0029_nft'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='token_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
