# Generated by Django 3.2.16 on 2023-04-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0030_nft_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digital_art',
            name='gen_image',
            field=models.ImageField(blank=True, default='default-noise.png', upload_to='generated_images/'),
        ),
    ]
