# Generated by Django 3.2.16 on 2023-04-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0032_alter_digital_art_gen_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digital_art',
            name='gen_image',
            field=models.ImageField(blank=True, default='default-noise_ea8wzb.png', null=True, upload_to='generated_images/'),
        ),
        migrations.AlterField(
            model_name='digital_art',
            name='init_image',
            field=models.ImageField(blank=True, default='default-noise_ea8wzb.png', upload_to='initial_images/'),
        ),
    ]
