# Generated by Django 3.2.16 on 2023-04-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftgen', '0033_auto_20230414_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digital_art',
            name='gen_image',
            field=models.ImageField(upload_to='generated_images/'),
        ),
        migrations.AlterField(
            model_name='nft_collection',
            name='logo',
            field=models.ImageField(default='default-collection_dfbpsd.jpg', upload_to='collection_logos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default-profile-pic_itkdbu.png', upload_to='profile_pics/'),
        ),
    ]
